# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e09e3e36892f9ec6a927d9b1af2a82e36c57158e946dbb47fd069d4dcb8d7ee8e3ccb3a7e50414b07bbe9e04fd7812ea7e1cac62bba947981ab3de9b0ab88a

test:
  secret_key_base: d36eb50095a17060a0ee3f6ca683bbff160aedd9f14d312c6631d1aaf995030e6c51a0d43413118de65fafa1eb9931f5c0064e3ebe34ffadd55858bde4d43e0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
